### ISSUE TITLE
Invalid application - no unmount function

### ISSUE THREAD

**Issue by shabsvs1** [single-spa/single-spa-react#116] opened 2021-06-30 12:32 UTC
Hi,@joeldenning 
I  created  a sample  react  application (using  create-single-spa  cli)   and  root  config app using  ( using  npx create-single-spa --moduleType root-config). I  registered  my application  in   root-config  with systemjs. But  i   getting below  error  while accessing the application.
![image](https://user-images.githubusercontent.com/31448761/123960292-c1a05c80-d9cc-11eb-9d18-c8149754efa0.png)
![image](https://user-images.githubusercontent.com/31448761/123960379-dc72d100-d9cc-11eb-81ee-ce3326d5b35b.png)
![image](https://user-images.githubusercontent.com/31448761/123960471-f3b1be80-d9cc-11eb-9afb-bb57bdec6e7d.png)

**Comment by joeldenning** [comment] 2021-07-03 23:27
I am unable to reproduce this problem - I created a fresh root config and single-spa application using create-single-spa and it worked. The most important information for diagnosing is the package.json and package-lock.json files, to see the versions of libraries. The best, though, would be to provide a github repo demonstrating the problem. I am closing this since I am unable to reproduce the problem and there was no demonstration of it given. Feel free to comment further, reopen, or create a new issue.

**Closed by joeldenning** 2021-07-03 23:27 UTC
