### ISSUE TITLE
A need for the default.default, when used as external dependency

### ISSUE THREAD

**Issue by madeofsun** [single-spa/single-spa-react#76] opened 2020-06-03 17:14 UTC
If the library is included as regular dependency as following, the importing syntax works as it should
```js
// index.js

import singleSpaReact from 'single-spa-react';

const lifecycles = singleSpaReact({
  React,
  ReactDOM,
  rootComponent
});
```
But I had to use this workaround 
```js
// index.js

import singleSpaReactModule from 'single-spa-react';

const lifecycles = singleSpaReactModule.default.default({
  React,
  ReactDOM,
  rootComponent
});
```
when the library is used as external systemjs dependency: 
```js
// webpack.config.js

const webpackMerge = require('webpack-merge');
const singleSpaDefaults = require('webpack-config-single-spa-react');

module.exports = (webpackConfigEnv) => {
  const defaultConfig = singleSpaDefaults({
    orgName: 'org',
    projectName: 'project',
    webpackConfigEnv
  });

  defaultConfig.externals.push('single-spa-react');

  ...
}
```

I think the following warning during umd-module compilation addresses this situation:

```console
$ rollup -c

src/single-spa-react.js → lib/single-spa-react.js...
(!) Mixing named and default exports
https://rollupjs.org/guide/en/#output-exports
The following entry modules are using named and default exports together:
src\single-spa-react.js

Consumers of your bundle will have to use chunk['default'] to access their default export, which may not be what you want. Use `output.exports: 'named'` to disable this warning
created lib/single-spa-react.js in 2s
Done in 2.70s.

```

**Comment by joeldenning** [comment] 2020-06-03 19:04
Thanks for the clear description of this issue. Generally, we don't actively encourage people to make single-spa-react a shared dependency since it's only about ~2kb gzipped and has multiple entry points (Both `import singleSpaReact from 'single-spa-react'` and `import Parcel from 'single-spa-react/parcel'`).

However, sharing this dependency as a systemjs module should be supported. I have reproduced the issue you have described in https://codesandbox.io/s/gallant-wu-ngxzp?file=/index.html:725-726.

I help maintain systemjs and the issue here is the interop layers between rollup and systemjs. SystemJS converts everything to an ES module namespace object, and UMD modules are not a ES module namespace object. To do the conversion, it makes the UMD module object as the default export. However, rollup's generated UMD module is also adding a default property to the UMD module, and hoping that the `__esModule` property will give correct hints to all interop layers. SystemJS does not support the `__esModule` property, since it is not on standards track.

I think the best solution here might be to publish a System.register version of single-spa-react (and maybe an ESM version as well, while we're at it). That would eliminate the problematic interop layers. We do this for the single-spa library as [shown here](https://unpkg.com/browse/single-spa@5.5.2/lib/) and [in this code](https://github.com/single-spa/single-spa/blob/master/rollup.config.js).

Do you have interest in putting a PR together for that? If not, I might have a chance to do so in the next few days.

**Comment by joeldenning** [comment] 2020-06-03 19:56
To clarify my suggested solution, here's what I think we should change the published files to look like:

```
lib/
--> umd/
----> single-spa-react.js
----> parcel.js
--> system/
----> single-spa-react.js
----> parcel.js
--> esm/
----> single-spa-react.js
----> parcel.js
package.json
```

Then the package.json would have the following:

```json
{
  "main": "lib/umd/single-spa-react.js",
  "module": "lib/esm/single-spa-react.js",
  "exports": {
    "import": {
      ".": "./lib/esm/single-spa-react.js",
      "./parcel": "./lib/esm/parcel.js"
    },
    "require": {
      ".": "./lib/umd/single-spa-react.js",
      "./parcel": "./lib/umd/parcel.js"
    }
  }
}
```

To use with import maps:
```html
<script type="importmap">
  {
    "imports": {
      "single-spa-react": "https://unpkg.com/single-spa-react/lib/esm/single-spa-react.js",
      "single-spa-react/": "https://unpkg.com/single-spa-react/lib/esm/"
    }
  }
</script>
<script type="module">
import singleSpaReact from 'single-spa-react';
import Parcel from 'single-spa-react/parcel.js"
</script>
```

To use as a webpack external within webpack:

```js
// This import remains the same
import singleSpaReact from 'single-spa-react';
// Breaking change - different path for importing parcels
import Parcel from 'single-spa-react/parcel.js'
```

To use as a build-time dependency with webpack. This would hopefully improve as webpack gains support for the `exports` field in the package.json:

```js
// This import remains the same
import singleSpaReact from 'single-spa-react';
// Breaking change - different path for importing parcels
import Parcel from 'single-spa-react/lib/umd/parcel.js'
```

I think that the breaking changes here would warrant publishing a new major version of single-spa-react. But I think that this is the better long term direction to take things?

@TheMcMurder @frehner @filoxo @blittle can you comment on this?

**Comment by frehner** [comment] 2020-06-03 21:42
>I think that the breaking changes here would warrant publishing a new major version of single-spa-react. But I think that this is the better long term direction to take things?

ah I was going to mention this, that it would be a breaking change (at the very least adding an exports map is)

Sounds good though. Do we also need to consider adding an ie11 esm build for bundlers and a pure esm build? (like we did in single-spa itself)

**Comment by madeofsun** [comment] 2020-06-04 07:24
Thank you for the quick and detailed answer.

While I was investigating the issue, I tried to see what will happen, if `System.register` is used.
The result was not satisfying - the import statement that should return the default export still gave the Module, but for this time it required only one '.default':

```js
import singleSpaReact from 'single-spa-react';

const lifecycles = singleSpaReact.default({
  React,
  ReactDOM,
  rootComponent
});
```

I have used the following `rollup.config.js` options for this, maybe I have missed something: 
```js
{
    input: "src/single-spa-react.js",
    output: {
      file: "lib/single-spa-react.js",
      format: "system",
      esModule: false, // I have tried with it and without, but as I understood, this option is skipped for system format
      sourcemap: true,
    },
    plugins: [babel(), terser()],
  }
```

And this warning about mixing of 'named' and 'default' exports still were there.

**Comment by joeldenning** [comment] 2020-06-04 18:32
> Do we also need to consider adding an ie11 esm build for bundlers and a pure esm build?

Good point, yes. The directory structure should match that of single-spa, which includes both `esm` and `es2015` builds - https://unpkg.com/browse/single-spa@5.5.3/lib/

> While I was investigating the issue, I tried to see what will happen, if System.register is used.
The result was not satisfying - the import statement that should return the default export still gave the Module, but for this time it required only one '.default':

Are you using webpack in the react project that imports single-spa-react? If so, which version of webpack? There was a bug in webpack in how it interpreted SystemJS modules that was recently fixed (see https://github.com/webpack/webpack/pull/10503). That fix was released in https://github.com/webpack/webpack/releases/tag/v5.0.0-beta.15. Upgrading to webpack 5 should solve that problem.

**Comment by madeofsun** [comment] 2020-06-05 06:24
Yeah, I have typical webpack config for single-spa-react app. Version 4, since 5 is in beta. I will check with the new version

**Comment by joeldenning** [comment] 2020-06-05 16:09
An alternative to upgrading to webpack 5 is using the __esModule systemjs extra described in https://github.com/launchdarkly/react-client-sdk/issues/36#issuecomment-633344790

**Comment by madeofsun** [comment] 2020-06-19 11:26
Still have not test with the new version of webpack, but the alternative solution works well.

**Closed** 2020-06-25 22:38 UTC

**Comment by joeldenning** [comment] 2020-06-26 17:58
System.register version published in https://github.com/single-spa/single-spa-react/releases/tag/v3.0.0, which does not have the default.default issue.
