### ISSUE TITLE
Webpack config issue, System.import returning invalid module

### ISSUE THREAD

**Issue by alanquigley-toast** [single-spa/single-spa-react#100] opened 2021-01-21 21:59 UTC
I'm trying to create a webpack configuration for a single SPA app, it builds, builds fails with this error:

<https://single-spa.js.org/error/?code=37&arg=application&arg=wex-banquet-root&arg={>

If I print out the return value from System.import it looks like this.

`Module {Symbol(Symbol.toStringTag): "Module"}`

I've inspected and compared with the webpack config generated by "create-single-spa" but I can decern any difference.

"does not export a bootstrap function or array of functions"

**Comment by alanquigley-toast** [comment] 2021-01-21 21:59
I'm hoping someone has run into a similar issue.

**Comment by joeldenning** [comment] 2021-01-21 22:11
This error means that the the webpack bundle is not exposing the exported lifecycle functions correctly. This can be caused by having multiple named entry points in the webpac config, or an array of entry points in the correct order (when `entry` is an array, only the last item in the array is exposed as the overall bundle's exports). The most common cause of this, though, is by using the SplitChunksPlugin, often via the webpack config `optimization` block. Specifically, `optimization.runtimeChunks` and `optimization.splitChunks` can result in the exports not being properly exposed from webpack to SystemJS.

You can read more info about what specific changes need to be made to a webpack config at https://single-spa.js.org/docs/recommended-setup#build-tools-webpack--rollup.

Closing this since it's not an issue with single-spa-react, but happy to discuss further if you have questions about any of the above.

**Closed by joeldenning** 2021-01-21 22:11 UTC

**Comment by alanquigley-toast** [comment] 2021-01-21 22:13
@joeldenning Thank you!

**Comment by alanquigley-toast** [comment] 2021-01-21 23:52
Not using the SplitChunksPlugin directly in the config, I tried breaking it down to the very minimal, same issue, does anything stand out here?

`
module.exports = {
  entry: './src/index.js',
  output: {
    filename: 'internal-spa.js',
    libraryTarget: 'system'
  },
  extensions: ['.js', '.jsx'],
  module: {
    rules: [
      {
        test: /\.(js|ts)x?$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env', '@babel/preset-react']
          }
        }
      }
    ]
  },
  externals: ['single-spa', 'react', 'react-dom'],
  devServer: {
    quiet: true,
    hot: true,
    historyApiFallback: true,
    headers: {
      'Access-Control-Allow-Origin': '*'
    },
    port: 9002
  }
}
`

**Comment by alanquigley-toast** [comment] 2021-01-22 17:21
So it looks like the issue was caused by `webpack-dev-server` using  `^4.0.0-beta.0` solved the issue.

**Comment by joeldenning** [comment] 2021-01-22 21:42
Ah yes, webpack-dev-server@4 is required when using webpack 5 to get some important bug fixes.

**Comment by Vipin-vis** [comment] 2021-06-30 12:06
Hi Joel, 
I am also facing same issue. When I tried to load a single spa react app its throwing
react_devtools_backend.js:2560 single-spa minified message #37: See [](https://single-spa.js.org/error/?code=37&arg=application&arg=@bh/dhp-issue&arg={}) error. This app was running smoothly till last Friday.

To check if the issue is due to version mismatch or something tried creating a fresh root config app and single react app. There also I am facing similar issue

**Comment by joeldenning** [comment] 2021-07-03 23:31
I tried creating a fresh root config and react application via create-single-spa and it all worked for me. There are some people on Slack who reported similar issues that seem related to webpack 5.40.0 - see https://single-spa.slack.com/archives/C8R6U7MT7/p1625009589354200. However, there's not enough information here to really know what's going on, since I wasn't able to reproduce the problem. Feel free to create a new issue with a demonstration of the problem.

**Comment by epikhighs** [comment] 2022-09-22 23:36
FYI disabling `optimization.runtimeChunk` and `optimization.splitChunks` by setting them to `false` fixed it for me.

**Comment by anwar-minst** [comment] 2024-10-17 07:47
facing same issue. i installed single-spa cli globally version (4.1.6)  and created root config and it's working perfectly but installed 5.0.0 and generated root config and facing same issue.
